name:	             hssnake
version:             0.1.0.0
github:              "orouvinen/hsworm"
license:             BSD3
author:              "Olli Rouvinen"
maintainer:          "example@example.com"
copyright:           "2019 Olli Rouvinen"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/orouvinen/hsworm#readme>

dependencies:
- base >= 4.7 && < 5
- ncurses
- mtl
- time
- containers
- random

library:
  source-dirs: src

executables:
  hssnake-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hssnake

tests:
  hssnake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hssnake
